version: '3.8'
services:
  postgres:
    env_file:
      - .env
    image: postgres
    container_name: nest_postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
